
version: '3.4'

services:
    db:
        image: postgres
        restart: always
        environment:
            - POSTGRES_USER=productcatalog
            - POSTGRES_PASSWORD=productcatalog
        ports:
            - '5432:5432'

    adminer:
        image: adminer
        restart: always
        ports:
            - "8080:8080"
        depends_on:
            - "db"

    api:
        build:
            context: .
            dockerfile: ProductCatalog.Api/Dockerfile
        restart: always
        ports:
            - "7144:80"
        environment:
            - ProductCatalogConnection=Host=db;Database=ProductCatalog;Username=productcatalog;Password=productcatalog
        depends_on:
            - "db"
    web:
        build:
            context: .
            dockerfile: ProductCatalog.Web/Dockerfile
        restart: always
        ports:
            - "4200:80"
        depends_on:
            - "api"
